services:
  bot:
    build:
      context: ./cmd
      dockerfile: Dockerfile
    environment:
      BOT_TOKEN: 6656048003:AAF9cTAOI8uTzMAQWtSr2L-WGCQE1Vw8fII 
      TG_BOT_URL: https://api.telegram.org/bot
      BOT_DB_HOST: db
      BOT_DB_PORT: 5432
      BOT_DB_USER: postgres
      BOT_DB_PASSWORD: postgres
      BOT_DB_NAME: bot
    depends_on:
      - db
    volumes:
      - "bot-logs:/bot-logs"

  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

volumes:
  postgres-data:
  bot-logs:
